apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis
spec:
  ports:
    - port: 6379
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-counter
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: counter
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: counter
    spec:
      containers:
        - name: counter
          image: ondrejsika/counter
          resources:
            requests:
              cpu: 40m
              memory: 40Mi
            limits:
              cpu: 80m
              memory: 80Mi
          env:
            - name: REDIS
              value: {{.Release.Name}}-redis
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-counter
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: counter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-counter
spec:
  rules:
    - host: {{ required ".Values.host is required" .Values.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}-counter
                port:
                  number: 80
